name: dart_sanity_client
description: A complete sanity.io http client. includes queries in grok and graphql(soon). Has methods for fetch, create, patch, and publish.
version: 0.1.1
repository: https://github.com/parkerhutchinson/dart_sanity_client

environment:
  sdk: ^3.6.0

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  dotenv: ^4.2.0
